# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
# s3
cloud:
  aws:
    s3:
      bucket: ${CLOUD.AWS.S3.BUCKETNAME}
    credentials:
      accessKey: ${CLOUD.AWS.CREDENTIALS.ACCESSKEY}
      secretKey: ${CLOUD.AWS.CREDENTIALS.SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false